version: '3'

services:
  
  dse:
    image: datastax/dse-server:6.0.2
    command: [ -s -g ]
    ports:
    - "9042:9042"
    - "8983:8983"
    - "8182:8182"
    environment:
      DS_LICENSE: accept
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
      
  studio:
    image: datastax/dse-studio:6.0.0
    ports:
    - "9091:9091"
    depends_on:
    - dse
    environment:
      SERVICE_9091_NAME: studio
      DS_LICENSE: accept
